### ISSUE TITLE
Question - why is octreedata needed

### ISSUE THREAD

**Issue by trsh** [Forceflow/ooc_svo_builder#64]
If octree, is the full octree. And it has it's nodes (filled or empty) on many levels, that can represent the actual voxels, for what we need another abstraction, like data?

**Comment by Forceflow** [comment]
I seperated the nodes from the actual data stored in the nodes since you often want to traverse the tree quickly (so a smaller data structure where more can be cached is beneficial), to finally end up in a certain node.

Once you know which node you want to look at, you can fetch the data for that node. There are pro's/cons to this approach, for example when you _know_ you're going to need the data of _every_ node you encounter during SVO traversal.
